sudo: required
services:
  - docker
  
before_install:
  - docker build -t mwaqasraza/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mwaqasraza/react-test npm test -- --coverage
 
after_success:
  - docker build -t jhelion/multi-client ./client
  - docker build -t jhelion/multi-nginx ./nginx
  - docker build -t jhelion/multi-server ./server
  - docker build -t jhelion/multi-worker ./worker