sudo: required
services:
  - docker

before_install:
  - docker build -t mwaqasraza/react-test -f ./client/Dockerfile.dev

script:
  - docker run mwaqasraza/react-test npm test -- --coverage

after_success:
  - docker build -t mwaqasraza/multi-client ./client
  - docker build -t mwaqasraza/multi-nginx ./nginx
  - docker build -t mwaqasraza/multi-server ./server
  - docker build -t mwaqasraza/multi-worker ./worker