sudo: required
services:
  - docker
  

before_install:
  - docker build -t mwaqasraza/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mwaqasraza/react-test npm test -- --coverage
 
after_success:
  - docker build -t mwaqasraza/multi-client ./client
  - docker build -t mwaqasraza/multi-nginx ./nginx
  - docker build -t mwaqasraza/multi-server ./server
  - docker build -t mwaqasraza/multi-worker ./worker
  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take all these build images to docker hub
  - docker push mwaqasraza/multi-client
  - docker push mwaqasraza/multi-nginx
  - docker push mwaqasraza/multi-server
  - docker push mwaqasraza/multi-worker
